version: "3"
services:
  database:
    image: postgres:11
    restart: always
    container_name: database_login
    ports:
      - 5432:5432
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./config/database/scripts:/docker-entrypoint-initdb.d
    networks:
      - networks_login

  server:
    container_name: services_login
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
    networks:
      - networks_login

volumes:
  postgres:

networks:
  networks_login:
    driver: bridge
